// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class remasteredStockModel6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remasteredStockModel6));
        
        string IMigrationMetadata.Id
        {
            get { return "201903151427472_remasteredStockModel6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
