// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class extOrderProblem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extOrderProblem));
        
        string IMigrationMetadata.Id
        {
            get { return "201903171100578_extOrderProblem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
