// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fix_order_feedbacks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_order_feedbacks));
        
        string IMigrationMetadata.Id
        {
            get { return "201903141350352_fix_order_feedbacks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
